version: '3'
services:
  mysql-db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
